### ISSUE TITLE
Small bugs when installing on fresh Ubuntu 16.04 server

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-install#40]
I just tried to install our SP on a fresh Ubuntu 16.04 server and noticed two small glitches where the installation aborts:

- Folder `/etc/ansible/group_vars` missing
    - Workaround: `sudo mkdir /etc/ansible/group_vars`
- Group `docker` missing
    - Workaround: `sudo groupadd docker`

I used the installation description provided on our webpage: http://sonata-nfv.eu/content/installation

**Comment by arocha7** [comment]
Hi Manuel, both issues are now fixed as below:

- group:
    name: docker
    state: present

- file:
    path: /etc/ansible/group_vars
    state: directory
    mode: 0755

Another recurrent issue: 
- sometimes, when the retrieve, of the Container images spends to much time, the playbook stops 

As a simple workaround, 
- just retry the playbook run, ie:

ubuntu@u16:~/son-install$ ansible-playbook son-cmud.yml -e "target=localhost operation=install service=all" --limit @/home/ubuntu/son-install/son-cmud.retry 

Nice to hear from you, Alberto
