### ISSUE TITLE
Duplicated dict key in destroy/ntp.yml

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-install#43]
[WARNING]: While constructing a mapping from /var/lib/jenkins/jobs/son-
install/workspace/destroy/ntp.yml, line 18, column 5, found a duplicate dict
key (when).  Using last defined value only.
[WARNING]: While constructing a mapping from /var/lib/jenkins/jobs/son-
install/workspace/destroy/ntp.yml, line 24, column 5, found a duplicate dict
key (when).  Using last defined value only.

**Comment by arocha7** [comment]
'destroy/sp/ntp.yml' fixed and tested - ok.
