### ISSUE TITLE
Deprecation warning command sudo

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-install#44]
Here are the list of files:
./deploy-terraform.yml
./deploy-pgsql.yml
./deploy-jenkins.yml
./destroy-pgsql.yml

[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default).
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

**Comment by arocha7** [comment]
resolved in v2.0
