### ISSUE TITLE
Databases are not initializated

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-install#62]
We got the following error:
```
D, [2017-04-16 21:45:08#14] DEBUG -- : PG::UndefinedTable: ERROR: relation "requests" does not exist
LINE 5: WHERE a.attrelid = '"requests"'::regclass
^
: SELECT a.attname, format_type(a.atttypid, a.atttypmod),
pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
FROM pg_attribute a LEFT JOIN pg_attrdef d
ON a.attrelid = d.adrelid AND a.attnum = d.adnum
WHERE a.attrelid = '"requests"'::regclass
AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
```
**Solution:**
`bundle exec rake db:migrate that has to be run`

**Comment by arocha7** [comment]
Need more info: 'bundle exec rake db:migrate ' is to be invoked at
* after the creation of the PostgreSQL database ?
* after the creation of each Container that has pgSQL connection ?

Example: ./roles/sp/tasks/gtk/srv.yml:
  - command: /usr/bin/docker exec -d son-gtksrv /bin/bash -c "cd /opt/sonata/son-gtksrv" && "bundle install" && "bundle exec rake db:migrate"
