### ISSUE TITLE
Change the deprecated option --link by --net and --network-alias in all playbooks

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-install#80]
We need to change the way to link the containers.

1. Create the network **sonata** in the VM
2. Start the containers in the network **sonata**
3. Create the **network alias** to the container in order to insert the record in the local network DNS.

**Comment by arocha7** [comment]
Fixed. Now is implemented with network name attached to the default Docker 'bridge' network - eg:
    networks:
      - name: bridge
        aliases: <xxx>
        links: <yyy>

After SP deploy, each Container interface can be check with:
*  sudo docker network ls
*  sudo docker inspect bridge 
More info here: https://docs.docker.com/engine/userguide/networking/
