### ISSUE TITLE
son-gtksrv is not configured to write logs in the right folder

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-install#84]
son-gtksrv have a volume created to write the logs but is not configured in the right folder
```
    volumes:
      - /home/{{ vm_user }}/son-gkeeper/son-gtksrv/:/opt/sonata/son-gktsrv
      - /var/log/sonata:/var/log/son-gtksrv
```

Also` /home/{{ vm_user }}/son-gkeeper/son-gtksrv/:/opt/sonata/son-gktsrv ` is not needed

**Comment by arocha7** [comment]
1. $HOME/son-gkeeper removed

2. - /var/log/sonata/son-gtksrv:/var/log/son-gtksrv
