### ISSUE TITLE
son-gtkfnct is not pointing to new catalogues url

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-install#85]
We have this configuration:
```
CATALOGUES_URL: http://{{ public_ip }}:4002/catalogues
```
We need to change it for this:
```
CATALOGUES_URL: http://{{ public_ip }}:4002/catalogues/api/v2
```

**Comment by arocha7** [comment]
grep -rl '4002/catalogues' | xargs sed -i 's/4002\/catalogues/4002\/catalogues\/api\/v2/g'

Affected 'docker_container': FNCT + SRV + PKG
